[2023-08-03 00:02:38,398] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 00:02:39,654] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 00:02:40,774] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 00:02:41,107] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 00:02:41,124] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 00:02:41,301] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 00:02:41,326] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 00:02:41,326] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 00:02:41,660] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 00:02:41,660] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 00:02:41,660] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 00:02:41,660] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 00:03:51,164] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 00:03:52,436] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 00:03:53,549] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 00:03:53,885] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 00:03:53,901] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 00:03:54,057] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 00:03:54,103] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 00:03:54,104] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 00:03:54,438] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 00:03:54,438] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 00:03:54,438] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 00:03:54,438] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 00:05:12,860] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 00:05:14,118] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 00:05:15,250] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 00:05:15,589] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 00:05:15,605] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 00:05:15,742] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 00:05:15,770] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 00:05:15,770] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 00:05:16,201] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 00:05:16,201] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 00:05:16,202] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 00:05:16,202] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 00:08:24,955] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 00:08:26,205] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 00:08:27,331] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 00:08:27,676] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 00:08:27,691] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 00:08:27,856] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 00:08:27,881] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 00:08:27,881] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 00:08:28,352] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 00:08:28,352] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 00:08:28,352] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 00:08:28,352] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 00:10:45,718] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 00:10:46,988] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 00:10:48,122] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 00:10:48,483] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 00:10:48,500] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 00:10:48,640] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 00:10:48,681] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 00:10:48,681] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 00:10:49,033] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 00:10:49,033] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 00:10:49,033] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 00:10:49,033] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 00:16:43,606] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 00:16:44,877] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 00:16:45,997] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 00:16:46,358] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 00:16:46,374] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 00:16:46,492] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 00:16:46,517] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 00:16:46,517] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 00:16:46,836] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 00:16:46,836] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 00:16:46,836] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 00:16:46,836] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 00:23:53,872] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 00:23:55,136] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 00:23:56,261] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 00:23:56,606] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 00:23:56,622] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 00:23:56,747] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 00:23:56,772] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 00:23:56,772] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 00:23:57,085] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 00:23:57,085] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 00:23:57,085] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 00:23:57,085] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 00:41:26,889] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 00:41:28,148] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 00:41:29,266] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 00:41:29,614] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 00:41:29,630] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 00:41:29,752] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 00:41:29,794] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 00:41:29,794] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 00:41:30,153] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 00:41:30,153] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 00:41:30,153] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 00:41:30,153] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 00:42:44,258] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 00:42:45,519] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 00:42:46,647] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 00:42:46,970] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 00:42:46,986] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 00:42:47,123] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 00:42:47,148] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 00:42:47,148] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 00:42:47,514] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 00:42:47,514] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 00:42:47,514] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 00:42:47,514] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 00:44:49,582] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 00:44:50,857] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 00:44:51,991] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 00:44:52,332] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 00:44:52,349] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 00:44:52,488] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 00:44:52,496] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 00:44:52,496] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 00:44:52,819] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 00:44:52,819] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 00:44:52,819] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 00:44:52,819] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 01:07:35,271] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 01:07:36,548] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 01:07:37,649] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 01:07:38,104] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 01:07:38,119] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 01:07:38,241] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 01:07:38,267] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 01:07:38,267] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 01:07:38,640] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 01:07:38,640] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 01:07:38,640] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 01:07:38,640] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 01:09:26,089] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 01:09:27,347] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 01:09:28,450] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 01:09:28,807] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 01:09:28,827] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 01:09:28,964] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 01:09:28,973] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 01:09:28,973] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 01:09:29,314] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 01:09:29,316] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 01:09:29,316] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 01:09:29,316] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 01:10:22,252] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 01:10:23,486] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 01:10:24,593] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 01:10:24,979] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 01:10:24,996] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 01:10:25,116] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 01:10:25,125] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 01:10:25,125] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 01:10:25,475] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 01:10:25,475] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 01:10:25,475] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 01:10:25,475] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 01:11:53,783] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 01:11:55,045] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 01:11:56,164] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 01:11:56,553] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 01:11:56,569] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 01:11:56,691] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 01:11:56,720] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 01:11:56,720] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 01:11:57,047] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 01:11:57,047] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 01:11:57,047] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 01:11:57,047] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 01:12:40,344] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 01:12:41,593] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 01:12:42,704] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 01:12:43,047] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 01:12:43,062] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 01:12:43,185] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 01:12:43,209] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 01:12:43,210] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 01:12:43,553] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 01:12:43,553] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 01:12:43,553] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 01:12:43,553] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 01:13:15,671] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 01:13:16,924] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 01:13:18,032] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 01:13:18,391] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 01:13:18,407] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 01:13:18,568] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 01:13:18,593] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 01:13:18,593] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 01:13:18,907] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 01:13:18,907] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 01:13:18,907] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 01:13:18,907] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 01:15:55,052] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 01:15:56,329] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 01:15:57,443] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 01:15:57,794] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 01:15:57,811] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 01:15:57,933] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 01:15:57,957] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 01:15:57,957] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 01:15:58,302] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 01:15:58,302] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 01:15:58,302] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 01:15:58,303] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 01:34:58,277] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 01:34:59,536] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 01:35:00,661] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 01:35:01,070] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 01:35:01,089] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 01:35:01,219] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 01:35:01,228] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 01:35:01,228] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 01:35:01,570] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 01:35:01,570] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 01:35:01,570] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 01:35:01,570] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 01:58:18,379] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 01:58:19,646] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 01:58:20,752] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 01:58:21,082] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 01:58:21,099] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 01:58:21,218] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 01:58:21,241] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 01:58:21,242] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 01:58:21,581] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 01:58:21,581] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 01:58:21,581] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 01:58:21,581] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 01:59:14,045] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 01:59:15,319] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 01:59:16,450] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 01:59:16,802] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 01:59:16,818] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 01:59:16,955] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 01:59:16,963] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 01:59:16,964] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 01:59:17,329] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 01:59:17,329] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 01:59:17,329] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 01:59:17,329] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 02:00:00,507] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 02:00:01,756] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 02:00:02,908] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 02:00:03,354] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 02:00:03,368] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 02:00:03,514] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 02:00:03,548] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 02:00:03,548] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 02:00:03,899] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 02:00:03,899] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 02:00:03,899] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 02:00:03,899] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 02:00:58,669] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 02:00:59,926] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 02:01:01,056] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 02:01:01,415] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 02:01:01,431] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 02:01:01,554] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 02:01:01,589] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 02:01:01,589] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 02:01:01,934] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 02:01:01,934] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 02:01:01,934] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 02:01:01,935] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 02:12:50,258] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 02:12:51,522] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 02:12:52,633] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 02:12:52,956] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 02:12:52,971] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 02:12:53,115] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 02:12:53,139] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 02:12:53,140] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 02:12:53,463] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 02:12:53,463] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 02:12:53,463] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 02:12:53,463] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 08:31:43,907] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 08:31:44,938] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 08:31:46,353] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 08:31:46,459] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 08:31:46,760] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 08:31:46,860] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 08:31:47,042] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 08:31:47,078] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 08:31:47,079] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 08:31:47,541] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 08:31:47,541] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 08:31:47,542] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 08:31:47,542] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 08:33:51,715] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 08:33:52,743] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 08:33:54,118] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 08:33:54,220] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 08:33:54,513] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 08:33:54,525] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 08:33:54,704] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 08:33:54,742] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 08:33:54,742] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 08:33:55,102] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 08:33:55,103] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 08:33:55,103] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 08:33:55,103] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 09:09:50,138] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 09:09:51,183] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 09:09:52,621] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 09:09:52,740] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 09:09:53,102] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 09:09:53,121] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 09:09:53,381] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 09:09:53,437] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 09:09:53,437] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 09:09:53,895] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 09:09:53,896] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 09:09:53,896] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 09:09:53,896] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 09:11:39,000] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 09:11:40,033] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 09:11:41,200] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 09:11:41,256] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 09:11:41,589] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 09:11:41,605] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 09:11:41,815] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 09:11:41,830] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 09:11:41,830] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 09:11:42,166] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 09:11:42,167] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 09:11:42,167] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 09:11:42,167] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 09:12:30,639] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 09:12:31,680] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 09:12:32,800] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 09:12:32,858] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 09:12:33,188] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 09:12:33,204] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 09:12:33,417] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 09:12:33,433] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 09:12:33,433] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 09:12:33,761] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 09:12:33,761] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 09:12:33,761] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 09:12:33,761] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 09:14:59,596] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 09:15:00,630] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 09:15:01,766] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 09:15:01,819] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 09:15:02,146] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 09:15:02,161] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 09:15:02,370] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 09:15:02,387] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 09:15:02,387] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 09:15:02,735] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 09:15:02,735] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 09:15:02,735] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 09:15:02,735] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 09:23:06,463] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 09:23:07,491] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 09:23:08,638] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 09:23:08,697] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 09:23:09,026] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 09:23:09,042] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 09:23:09,255] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 09:23:09,271] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 09:23:09,271] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 09:23:09,596] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 09:23:09,596] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 09:23:09,596] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 09:23:09,596] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 09:27:12,639] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 09:27:13,673] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 09:27:14,774] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 09:27:14,840] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 09:27:15,189] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 09:27:15,208] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 09:27:15,424] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 09:27:15,472] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 09:27:15,472] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 09:27:15,841] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 09:27:15,841] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 09:27:15,841] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 09:27:15,841] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 09:29:09,141] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 09:29:10,178] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 09:29:11,326] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 09:29:11,387] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 09:29:11,726] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 09:29:11,743] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 09:29:11,958] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 09:29:11,974] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 09:29:11,974] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 09:29:12,317] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 09:29:12,318] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 09:29:12,318] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 09:29:12,318] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 09:35:07,947] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 09:35:08,975] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 09:35:10,119] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 09:35:10,179] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 09:35:10,569] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 09:35:10,586] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 09:35:10,803] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 09:35:10,820] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 09:35:10,820] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 09:35:11,161] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 09:35:11,161] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 09:35:11,161] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 09:35:11,161] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 09:38:10,047] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 09:38:11,081] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 09:38:12,226] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 09:38:12,287] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 09:38:12,641] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 09:38:12,658] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 09:38:12,883] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 09:38:12,900] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 09:38:12,900] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 09:38:13,255] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 09:38:13,255] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 09:38:13,255] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 09:38:13,255] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 09:47:38,514] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 09:47:39,559] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 09:47:41,029] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 09:47:41,167] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 09:47:41,529] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 09:47:41,548] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 09:47:41,770] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 09:47:41,816] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 09:47:41,817] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 09:47:42,275] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 09:47:42,275] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 09:47:42,275] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 09:47:42,275] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 09:54:35,426] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 09:54:36,478] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 09:54:37,961] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 09:54:38,081] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 09:54:38,452] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 09:54:38,471] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 09:54:38,697] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 09:54:38,743] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 09:54:38,743] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 09:54:39,204] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 09:54:39,204] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 09:54:39,204] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 09:54:39,204] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 10:04:57,112] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 10:04:58,159] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 10:04:59,307] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 10:04:59,374] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 10:04:59,739] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 10:04:59,758] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 10:04:59,996] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 10:05:00,014] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 10:05:00,014] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 10:05:00,371] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 10:05:00,371] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 10:05:00,371] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 10:05:00,371] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 10:29:56,182] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 10:29:57,221] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 10:29:58,747] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 10:29:58,875] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 10:29:59,257] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 10:29:59,282] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 10:29:59,517] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 10:29:59,564] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 10:29:59,564] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 10:30:00,045] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 10:30:00,045] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 10:30:00,045] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 10:30:00,045] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 10:31:09,472] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 10:31:10,508] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 10:31:11,655] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 10:31:11,726] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 10:31:12,119] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 10:31:12,138] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 10:31:12,383] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 10:31:12,401] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 10:31:12,401] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 10:31:12,774] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 10:31:12,774] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 10:31:12,774] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 10:31:12,774] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 10:32:02,011] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 10:32:03,043] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 10:32:04,182] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 10:32:04,257] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 10:32:04,652] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 10:32:04,672] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 10:32:04,898] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 10:32:04,914] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 10:32:04,915] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 10:32:05,298] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 10:32:05,298] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 10:32:05,298] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 10:32:05,298] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 11:26:18,947] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 11:26:19,976] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 11:26:21,338] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 11:26:21,436] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 11:26:21,743] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 11:26:21,759] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 11:26:21,938] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 11:26:21,978] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 11:26:21,978] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 11:26:22,362] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 11:26:22,362] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 11:26:22,362] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 11:26:22,362] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 11:27:45,002] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 11:27:46,032] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 11:27:47,117] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 11:27:47,167] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 11:27:47,465] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 11:27:47,478] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 11:27:47,656] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 11:27:47,670] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 11:27:47,670] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 11:27:47,962] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 11:27:47,962] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 11:27:47,963] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 11:27:47,963] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 11:28:34,834] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 11:28:35,862] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 11:28:36,947] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 11:28:36,996] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 11:28:37,289] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 11:28:37,303] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 11:28:37,492] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 11:28:37,506] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 11:28:37,506] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 11:28:37,817] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 11:28:37,818] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 11:28:37,818] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 11:28:37,818] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 11:31:32,892] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 11:31:33,934] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 11:31:35,025] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 11:31:35,075] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 11:31:35,365] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 11:31:35,380] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 11:31:35,567] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 11:31:35,580] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 11:31:35,581] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 11:31:35,872] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 11:31:35,872] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 11:31:35,872] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 11:31:35,872] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 12:43:51,509] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 12:43:52,535] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 12:43:53,916] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 12:43:54,018] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 12:43:54,330] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 12:43:54,345] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 12:43:54,529] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 12:43:54,570] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 12:43:54,570] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 12:43:54,974] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 12:43:54,974] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 12:43:54,974] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 12:43:54,974] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 12:45:25,323] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 12:45:26,349] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 12:45:27,437] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 12:45:27,488] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 12:45:27,781] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 12:45:27,795] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 12:45:27,979] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 12:45:27,992] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 12:45:27,993] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 12:45:28,278] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 12:45:28,278] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 12:45:28,278] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 12:45:28,278] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 13:09:19,153] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 13:09:20,177] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 13:09:21,553] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 13:09:21,669] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 13:09:21,977] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 13:09:21,994] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 13:09:22,183] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 13:09:22,222] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 13:09:22,222] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 13:09:22,613] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 13:09:22,614] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 13:09:22,614] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 13:09:22,614] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 13:11:49,965] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 13:11:50,993] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 13:11:52,358] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 13:11:52,461] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 13:11:52,765] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 13:11:52,781] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 13:11:52,965] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 13:11:53,003] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 13:11:53,003] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 13:11:53,381] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 13:11:53,381] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 13:11:53,382] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 13:11:53,382] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 13:16:44,420] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 13:16:45,450] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 13:16:46,534] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 13:16:46,586] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 13:16:46,877] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 13:16:46,890] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 13:16:47,065] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 13:16:47,080] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 13:16:47,080] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 13:16:47,378] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 13:16:47,378] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 13:16:47,378] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 13:16:47,378] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 13:18:51,870] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 13:18:52,908] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 13:18:54,004] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 13:18:54,058] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 13:18:54,385] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 13:18:54,399] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 13:18:54,581] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 13:18:54,595] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 13:18:54,595] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 13:18:54,890] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 13:18:54,890] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 13:18:54,890] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 13:18:54,890] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 13:21:08,946] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 13:21:09,977] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 13:21:11,075] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 13:21:11,125] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 13:21:11,417] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 13:21:11,430] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 13:21:11,610] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 13:21:11,623] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 13:21:11,623] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 13:21:11,910] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 13:21:11,910] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 13:21:11,910] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 13:21:11,910] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 13:22:11,698] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 13:22:12,724] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 13:22:13,826] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 13:22:13,879] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 13:22:14,176] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 13:22:14,190] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 13:22:14,378] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 13:22:14,392] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 13:22:14,392] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 13:22:14,675] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 13:22:14,675] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 13:22:14,676] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 13:22:14,676] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 13:25:54,582] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 13:25:55,611] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 13:25:56,966] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 13:25:57,067] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 13:25:57,374] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 13:25:57,389] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 13:25:57,573] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 13:25:57,610] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 13:25:57,610] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 13:25:57,989] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 13:25:57,989] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 13:25:57,989] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 13:25:57,989] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 13:28:03,325] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 13:28:04,353] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 13:28:05,441] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 13:28:05,492] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 13:28:05,778] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 13:28:05,793] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 13:28:05,968] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 13:28:05,983] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 13:28:05,983] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 13:28:06,279] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 13:28:06,279] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 13:28:06,279] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 13:28:06,279] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 13:40:03,591] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 13:40:04,622] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 13:40:06,001] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 13:40:06,098] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 13:40:06,402] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 13:40:06,416] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 13:40:06,606] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 13:40:06,643] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 13:40:06,643] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 13:40:07,026] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 13:40:07,026] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 13:40:07,026] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 13:40:07,026] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 13:49:15,404] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 13:49:16,439] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 13:49:17,524] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 13:49:17,572] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 13:49:17,872] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 13:49:17,885] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 13:49:18,064] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 13:49:18,079] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 13:49:18,079] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 13:49:18,388] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 13:49:18,388] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 13:49:18,388] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 13:49:18,388] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 13:49:46,876] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 13:49:47,908] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 13:49:48,997] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 13:49:49,048] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 13:49:49,359] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 13:49:49,373] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 13:49:49,556] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 13:49:49,570] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 13:49:49,571] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 13:49:49,867] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 13:49:49,867] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 13:49:49,867] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 13:49:49,867] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 13:54:26,043] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 13:54:27,072] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 13:54:28,160] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 13:54:28,208] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 13:54:28,542] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 13:54:28,556] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 13:54:28,735] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 13:54:28,748] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 13:54:28,748] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 13:54:29,037] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 13:54:29,037] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 13:54:29,037] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 13:54:29,037] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 13:59:25,963] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 13:59:26,993] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 13:59:28,346] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 13:59:28,444] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 13:59:28,750] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 13:59:28,764] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 13:59:28,953] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 13:59:28,990] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 13:59:28,991] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 13:59:29,374] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 13:59:29,374] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 13:59:29,374] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 13:59:29,374] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 14:01:47,924] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 14:01:48,952] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 14:01:50,036] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 14:01:50,085] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 14:01:50,382] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 14:01:50,396] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 14:01:50,584] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 14:01:50,598] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 14:01:50,598] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 14:01:50,882] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 14:01:50,882] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 14:01:50,882] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 14:01:50,882] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-08-03 14:06:19,406] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-08-03 14:06:20,434] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-08-03 14:06:21,517] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\RobotControl\Robot.cs:line 460
[2023-08-03 14:06:21,567] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\TesterSequence\TesterSeq.cs:line 497
[2023-08-03 14:06:21,853] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\CameraControl\Camera_Control.cs:line 264
[2023-08-03 14:06:21,867] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-08-03 14:06:22,052] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla\PIControl\PI_Control.cs:line 160
[2023-08-03 14:06:22,066] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-08-03 14:06:22,066] [INFO] [MACHINE] - HMI Version:1.0.0.0---Vision Version:3.6.0.0---Robot Version:
[2023-08-03 14:06:22,354] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-08-03 14:06:22,355] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-08-03 14:06:22,355] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-08-03 14:06:22,355] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
