[2023-07-31 08:21:09,476] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-07-31 08:21:12,034] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-07-31 08:21:14,106] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla_3072023\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla_3072023\RobotControl\Robot.cs:line 460
[2023-07-31 08:21:38,345] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\TesterSequence\TesterSeq.cs:line 496
[2023-07-31 08:22:01,706] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\Duong Van Hoan\Desktop\Porla\Porla_3072023\CameraControl\Camera_Control.cs:line 264
[2023-07-31 08:22:19,794] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-07-31 08:22:19,982] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 160
[2023-07-31 08:22:19,995] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-07-31 08:22:19,995] [INFO] [MACHINE] - HMI Version:1.0.0.2---Vision Version:3.6.0.0---Robot Version:
[2023-07-31 08:22:20,185] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-07-31 08:22:20,185] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-07-31 08:22:20,185] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-07-31 08:22:20,185] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-07-31 08:22:40,326] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-07-31 08:22:42,838] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-07-31 08:22:44,294] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 460
[2023-07-31 08:22:44,343] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\TesterSequence\TesterSeq.cs:line 496
[2023-07-31 08:22:44,649] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\CameraControl\Camera_Control.cs:line 264
[2023-07-31 08:22:44,650] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-07-31 08:22:44,821] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 160
[2023-07-31 08:22:44,830] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-07-31 08:22:44,830] [INFO] [MACHINE] - HMI Version:1.0.0.2---Vision Version:3.6.0.0---Robot Version:
[2023-07-31 08:22:45,003] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-07-31 08:22:45,003] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-07-31 08:22:45,003] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-07-31 08:22:45,003] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-07-31 08:23:41,061] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-07-31 08:23:42,074] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-07-31 08:23:43,129] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 460
[2023-07-31 08:23:43,177] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\TesterSequence\TesterSeq.cs:line 496
[2023-07-31 08:23:43,507] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\CameraControl\Camera_Control.cs:line 264
[2023-07-31 08:23:43,518] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-07-31 08:23:43,696] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 160
[2023-07-31 08:23:43,712] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-07-31 08:23:43,712] [INFO] [MACHINE] - HMI Version:1.0.0.2---Vision Version:3.6.0.0---Robot Version:
[2023-07-31 08:23:43,891] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-07-31 08:23:43,892] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-07-31 08:23:43,892] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-07-31 08:23:43,892] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-07-31 08:26:47,573] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-07-31 08:26:48,601] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-07-31 08:26:49,678] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 460
[2023-07-31 08:26:49,726] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\TesterSequence\TesterSeq.cs:line 496
[2023-07-31 08:26:50,041] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\CameraControl\Camera_Control.cs:line 264
[2023-07-31 08:26:50,053] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-07-31 08:26:50,231] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 160
[2023-07-31 08:26:50,249] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-07-31 08:26:50,249] [INFO] [MACHINE] - HMI Version:1.0.0.2---Vision Version:3.6.0.0---Robot Version:
[2023-07-31 08:26:50,426] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-07-31 08:26:50,426] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-07-31 08:26:50,426] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-07-31 08:26:50,426] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-07-31 08:30:02,827] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-07-31 08:30:03,858] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-07-31 08:30:04,939] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 460
[2023-07-31 08:30:04,986] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\TesterSequence\TesterSeq.cs:line 496
[2023-07-31 08:30:05,305] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\CameraControl\Camera_Control.cs:line 264
[2023-07-31 08:30:05,318] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-07-31 08:30:05,489] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 160
[2023-07-31 08:30:05,506] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-07-31 08:30:05,506] [INFO] [MACHINE] - HMI Version:1.0.0.2---Vision Version:3.6.0.0---Robot Version:
[2023-07-31 08:30:05,678] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-07-31 08:30:05,678] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-07-31 08:30:05,678] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-07-31 08:30:05,678] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-07-31 08:31:28,771] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-07-31 08:31:29,800] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-07-31 08:31:30,882] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 460
[2023-07-31 08:31:30,929] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\TesterSequence\TesterSeq.cs:line 496
[2023-07-31 08:31:31,242] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\CameraControl\Camera_Control.cs:line 264
[2023-07-31 08:31:31,254] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-07-31 08:31:31,429] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 160
[2023-07-31 08:31:31,445] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-07-31 08:31:31,445] [INFO] [MACHINE] - HMI Version:1.0.0.2---Vision Version:3.6.0.0---Robot Version:
[2023-07-31 08:31:31,621] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-07-31 08:31:31,621] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-07-31 08:31:31,621] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-07-31 08:31:31,621] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-07-31 08:33:34,009] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-07-31 08:33:35,038] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-07-31 08:33:36,124] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 460
[2023-07-31 08:33:36,177] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\TesterSequence\TesterSeq.cs:line 497
[2023-07-31 08:33:36,501] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\CameraControl\Camera_Control.cs:line 264
[2023-07-31 08:33:36,512] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-07-31 08:33:36,682] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 160
[2023-07-31 08:33:36,699] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-07-31 08:33:36,700] [INFO] [MACHINE] - HMI Version:1.0.0.2---Vision Version:3.6.0.0---Robot Version:
[2023-07-31 08:33:36,876] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-07-31 08:33:36,876] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-07-31 08:33:36,876] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-07-31 08:33:36,876] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-07-31 09:00:27,496] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-07-31 09:00:28,548] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-07-31 09:00:30,033] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 460
[2023-07-31 09:00:30,156] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\TesterSequence\TesterSeq.cs:line 497
[2023-07-31 09:00:30,543] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\CameraControl\Camera_Control.cs:line 264
[2023-07-31 09:00:30,560] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-07-31 09:00:30,769] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 160
[2023-07-31 09:00:30,814] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-07-31 09:00:30,815] [INFO] [MACHINE] - HMI Version:1.0.0.2---Vision Version:3.6.0.0---Robot Version:
[2023-07-31 09:00:31,163] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-07-31 09:00:31,163] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-07-31 09:00:31,163] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-07-31 09:00:31,163] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-07-31 09:02:28,309] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-07-31 09:02:29,345] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-07-31 09:02:30,487] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 460
[2023-07-31 09:02:30,545] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\TesterSequence\TesterSeq.cs:line 497
[2023-07-31 09:02:30,914] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\CameraControl\Camera_Control.cs:line 264
[2023-07-31 09:02:30,930] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-07-31 09:02:31,143] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 160
[2023-07-31 09:02:31,163] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-07-31 09:02:31,163] [INFO] [MACHINE] - HMI Version:1.0.0.2---Vision Version:3.6.0.0---Robot Version:
[2023-07-31 09:02:31,376] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-07-31 09:02:31,376] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-07-31 09:02:31,377] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-07-31 09:02:31,377] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-07-31 09:05:24,310] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-07-31 09:05:25,343] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-07-31 09:05:26,456] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 460
[2023-07-31 09:05:26,514] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\TesterSequence\TesterSeq.cs:line 497
[2023-07-31 09:05:26,887] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\CameraControl\Camera_Control.cs:line 264
[2023-07-31 09:05:26,904] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-07-31 09:05:27,121] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 160
[2023-07-31 09:05:27,142] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-07-31 09:05:27,142] [INFO] [MACHINE] - HMI Version:1.0.0.2---Vision Version:3.6.0.0---Robot Version:
[2023-07-31 09:05:27,357] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-07-31 09:05:27,357] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-07-31 09:05:27,357] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-07-31 09:05:27,357] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-07-31 09:08:18,300] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-07-31 09:08:19,344] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-07-31 09:08:20,531] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 460
[2023-07-31 09:08:20,593] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\TesterSequence\TesterSeq.cs:line 497
[2023-07-31 09:08:20,976] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\CameraControl\Camera_Control.cs:line 264
[2023-07-31 09:08:20,991] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-07-31 09:08:21,206] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 160
[2023-07-31 09:08:21,227] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-07-31 09:08:21,228] [INFO] [MACHINE] - HMI Version:1.0.0.2---Vision Version:3.6.0.0---Robot Version:
[2023-07-31 09:08:21,438] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-07-31 09:08:21,439] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-07-31 09:08:21,439] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-07-31 09:08:21,439] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-07-31 09:09:28,159] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-07-31 09:09:29,187] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-07-31 09:09:30,282] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 460
[2023-07-31 09:09:30,338] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\TesterSequence\TesterSeq.cs:line 497
[2023-07-31 09:09:30,697] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\CameraControl\Camera_Control.cs:line 264
[2023-07-31 09:09:30,712] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-07-31 09:09:30,923] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 160
[2023-07-31 09:09:30,942] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-07-31 09:09:30,942] [INFO] [MACHINE] - HMI Version:1.0.0.2---Vision Version:3.6.0.0---Robot Version:
[2023-07-31 09:09:31,152] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-07-31 09:09:31,152] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-07-31 09:09:31,152] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-07-31 09:09:31,152] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-07-31 09:11:11,029] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-07-31 09:11:12,069] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-07-31 09:11:13,177] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 460
[2023-07-31 09:11:13,235] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\TesterSequence\TesterSeq.cs:line 497
[2023-07-31 09:11:13,605] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\CameraControl\Camera_Control.cs:line 264
[2023-07-31 09:11:13,620] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-07-31 09:11:13,831] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 160
[2023-07-31 09:11:13,850] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-07-31 09:11:13,851] [INFO] [MACHINE] - HMI Version:1.0.0.2---Vision Version:3.6.0.0---Robot Version:
[2023-07-31 09:11:14,060] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-07-31 09:11:14,060] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-07-31 09:11:14,060] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-07-31 09:11:14,060] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-07-31 09:11:47,197] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-07-31 09:11:48,245] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-07-31 09:11:49,386] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 460
[2023-07-31 09:11:49,444] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\TesterSequence\TesterSeq.cs:line 497
[2023-07-31 09:11:49,808] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\CameraControl\Camera_Control.cs:line 264
[2023-07-31 09:11:49,823] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-07-31 09:11:50,031] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 160
[2023-07-31 09:11:50,052] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-07-31 09:11:50,052] [INFO] [MACHINE] - HMI Version:1.0.0.2---Vision Version:3.6.0.0---Robot Version:
[2023-07-31 09:11:50,270] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-07-31 09:11:50,270] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-07-31 09:11:50,270] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-07-31 09:11:50,270] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-07-31 09:13:34,849] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-07-31 09:13:35,879] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-07-31 09:13:37,009] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 460
[2023-07-31 09:13:37,069] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\TesterSequence\TesterSeq.cs:line 497
[2023-07-31 09:13:37,437] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\CameraControl\Camera_Control.cs:line 264
[2023-07-31 09:13:37,453] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-07-31 09:13:37,661] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 160
[2023-07-31 09:13:37,682] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-07-31 09:13:37,683] [INFO] [MACHINE] - HMI Version:1.0.0.2---Vision Version:3.6.0.0---Robot Version:
[2023-07-31 09:13:37,895] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-07-31 09:13:37,895] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-07-31 09:13:37,895] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-07-31 09:13:37,895] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-07-31 09:15:11,849] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-07-31 09:15:12,889] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-07-31 09:15:14,029] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 460
[2023-07-31 09:15:14,087] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\TesterSequence\TesterSeq.cs:line 497
[2023-07-31 09:15:14,461] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\CameraControl\Camera_Control.cs:line 264
[2023-07-31 09:15:14,476] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-07-31 09:15:14,687] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 160
[2023-07-31 09:15:14,704] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-07-31 09:15:14,704] [INFO] [MACHINE] - HMI Version:1.0.0.2---Vision Version:3.6.0.0---Robot Version:
[2023-07-31 09:15:14,920] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-07-31 09:15:14,920] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-07-31 09:15:14,920] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-07-31 09:15:14,920] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-07-31 09:15:39,953] [ERROR] [MACHINE] - IO Module | Set digital output failed!
[2023-07-31 09:18:04,933] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-07-31 09:18:05,985] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-07-31 09:18:07,151] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 460
[2023-07-31 09:18:07,208] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\TesterSequence\TesterSeq.cs:line 497
[2023-07-31 09:18:07,616] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\CameraControl\Camera_Control.cs:line 264
[2023-07-31 09:18:07,631] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-07-31 09:18:07,845] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 160
[2023-07-31 09:18:07,866] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-07-31 09:18:07,866] [INFO] [MACHINE] - HMI Version:1.0.0.2---Vision Version:3.6.0.0---Robot Version:
[2023-07-31 09:18:08,079] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-07-31 09:18:08,079] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-07-31 09:18:08,079] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-07-31 09:18:08,079] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-07-31 14:28:14,808] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-07-31 14:28:15,837] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-07-31 14:28:16,935] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 460
[2023-07-31 14:28:16,996] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\TesterSequence\TesterSeq.cs:line 497
[2023-07-31 14:28:17,337] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\CameraControl\Camera_Control.cs:line 264
[2023-07-31 14:28:17,351] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-07-31 14:28:17,551] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 160
[2023-07-31 14:28:17,566] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-07-31 14:28:17,566] [INFO] [MACHINE] - HMI Version:1.0.0.2---Vision Version:3.6.0.0---Robot Version:
[2023-07-31 14:28:17,788] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-07-31 14:28:17,788] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-07-31 14:28:17,788] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-07-31 14:28:17,788] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-07-31 16:09:13,200] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-07-31 16:09:14,225] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-07-31 16:09:15,606] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 460
[2023-07-31 16:09:15,714] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\TesterSequence\TesterSeq.cs:line 497
[2023-07-31 16:09:16,077] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\CameraControl\Camera_Control.cs:line 264
[2023-07-31 16:09:16,095] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-07-31 16:09:16,290] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 160
[2023-07-31 16:09:16,324] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-07-31 16:09:16,324] [INFO] [MACHINE] - HMI Version:1.0.0.2---Vision Version:3.6.0.0---Robot Version:
[2023-07-31 16:09:16,648] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-07-31 16:09:16,648] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-07-31 16:09:16,648] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-07-31 16:09:16,648] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-07-31 16:10:01,051] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-07-31 16:10:02,080] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-07-31 16:10:03,174] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 460
[2023-07-31 16:10:03,227] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\TesterSequence\TesterSeq.cs:line 497
[2023-07-31 16:10:03,562] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\CameraControl\Camera_Control.cs:line 264
[2023-07-31 16:10:03,576] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-07-31 16:10:03,761] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 160
[2023-07-31 16:10:03,776] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-07-31 16:10:03,777] [INFO] [MACHINE] - HMI Version:1.0.0.2---Vision Version:3.6.0.0---Robot Version:
[2023-07-31 16:10:03,972] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-07-31 16:10:03,972] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-07-31 16:10:03,972] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-07-31 16:10:03,972] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-07-31 16:27:34,630] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-07-31 16:27:35,655] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-07-31 16:27:37,019] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 460
[2023-07-31 16:27:37,117] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\TesterSequence\TesterSeq.cs:line 497
[2023-07-31 16:27:37,486] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\CameraControl\Camera_Control.cs:line 264
[2023-07-31 16:27:37,503] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-07-31 16:27:37,689] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 160
[2023-07-31 16:27:37,728] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-07-31 16:27:37,728] [INFO] [MACHINE] - HMI Version:1.0.0.2---Vision Version:3.6.0.0---Robot Version:
[2023-07-31 16:27:38,040] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-07-31 16:27:38,040] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-07-31 16:27:38,040] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-07-31 16:27:38,040] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-07-31 16:28:58,289] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-07-31 16:28:59,317] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-07-31 16:29:00,404] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 460
[2023-07-31 16:29:00,463] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\TesterSequence\TesterSeq.cs:line 497
[2023-07-31 16:29:00,802] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\CameraControl\Camera_Control.cs:line 264
[2023-07-31 16:29:00,814] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-07-31 16:29:01,008] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 160
[2023-07-31 16:29:01,020] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-07-31 16:29:01,021] [INFO] [MACHINE] - HMI Version:1.0.0.2---Vision Version:3.6.0.0---Robot Version:
[2023-07-31 16:29:01,220] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-07-31 16:29:01,220] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-07-31 16:29:01,220] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-07-31 16:29:01,220] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-07-31 16:30:58,108] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-07-31 16:30:59,144] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-07-31 16:31:00,241] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 460
[2023-07-31 16:31:00,288] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\TesterSequence\TesterSeq.cs:line 497
[2023-07-31 16:31:00,663] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\CameraControl\Camera_Control.cs:line 264
[2023-07-31 16:31:00,678] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-07-31 16:31:00,873] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 160
[2023-07-31 16:31:00,889] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-07-31 16:31:00,889] [INFO] [MACHINE] - HMI Version:1.0.0.2---Vision Version:3.6.0.0---Robot Version:
[2023-07-31 16:31:01,091] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-07-31 16:31:01,092] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-07-31 16:31:01,092] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-07-31 16:31:01,092] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-07-31 16:36:18,406] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-07-31 16:36:19,431] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-07-31 16:36:20,817] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 460
[2023-07-31 16:36:20,921] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\TesterSequence\TesterSeq.cs:line 497
[2023-07-31 16:36:21,281] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\CameraControl\Camera_Control.cs:line 264
[2023-07-31 16:36:21,296] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-07-31 16:36:21,488] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 160
[2023-07-31 16:36:21,523] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-07-31 16:36:21,523] [INFO] [MACHINE] - HMI Version:1.0.0.2---Vision Version:3.6.0.0---Robot Version:
[2023-07-31 16:36:21,830] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-07-31 16:36:21,831] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-07-31 16:36:21,831] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-07-31 16:36:21,831] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
[2023-07-31 16:39:40,663] [ERROR] [MACHINE] - IO Module | Connect to 192.168.2.1 failed
[2023-07-31 16:39:41,692] [ERROR] [MACHINE] - IO Module | Connect to 192.168.3.1 failed
[2023-07-31 16:39:42,780] [ERROR] [MACHINE] - Robot | System.ComponentModel.Win32Exception (0x80004005): Class not registered

Class not registered

   at Adapters.NetscanAdapter.Scan()
   at ControllerAPI.Internal.NetworkScannerInternal.GetControllers()
   at ABB.Robotics.Controllers.Discovery.NetworkScanner.Scan()
   at RobotControl.Robot.FindControllers() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 868
   at RobotControl.Robot.ConnectRobot() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\RobotControl\Robot.cs:line 460
[2023-07-31 16:39:42,832] [ERROR] [MACHINE] - Tester | Create Folder ErrorSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ARES\Summary'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at TesterSequence.TesterSeq.Create_Folder_Project() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\TesterSequence\TesterSeq.cs:line 497
[2023-07-31 16:39:43,169] [ERROR] [MACHINE] - Camera | System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Pylon.DeviceInfoList.{ctor}(DeviceInfoList* )
   at Basler.Pylon.CameraFinder.Enumerate()
   at CameraControl.Camera_Control.UpdateDeviceList() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\CameraControl\Camera_Control.cs:line 264
[2023-07-31 16:39:43,184] [INFO] [MACHINE] - Actuator | -- Try to Search devide --
[2023-07-31 16:39:43,368] [ERROR] [MACHINE] - Actuator | Initialize axis no: 1 fail, with exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PI.GCS2.EnumerateUSB(StringBuilder sBuffer, Int32 iBufferSize, String sFilter)
   at PIControl.PI_Control.SearchDevice(ConnectionType type, String hostName) in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 479
   at PIControl.PI_Control.Initialize() in C:\Users\hoanvduong\Desktop\Porla\PorlaSorftware\Porla_3072023\PIControl\PI_Control.cs:line 160
[2023-07-31 16:39:43,383] [INFO] [MACHINE] - ARES HMI Initialize Successful!
[2023-07-31 16:39:43,383] [INFO] [MACHINE] - HMI Version:1.0.0.2---Vision Version:3.6.0.0---Robot Version:
[2023-07-31 16:39:43,583] [INFO] [MACHINE] - Alarm | Alarm Occured - Robot not connected
[2023-07-31 16:39:43,584] [INFO] [MACHINE] - Alarm | Alarm Occured - Actuator Not Connected
[2023-07-31 16:39:43,584] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 1 Not Connected
[2023-07-31 16:39:43,584] [INFO] [MACHINE] - Alarm | Alarm Occured - IO Module 2 Not Connected
